import {
  CheckInHistory,
  ClassScheduleItem,
  ClassTaken,
  EnrolledBooking,
  Invoice,
  Member,
  Product,
  AnalyticsStatistic,
  MembershipGrowth,
  ClassAttendance,
  TargetRevenue,
  ActiveHours,
} from '@/types/shared';

// Mock data for Member Detail Page - In a real app, this would come from an API
export const mockMember: Member = {
  user_id: '1',
  first_name: 'John',
  last_name: 'Doe',
  email: 'john.doe@example.com',
  phone: '1234567890',
  membership_plan: 'Basic',
  created_at: '2021-01-01',
  user_image: '',
  role_name: 'member',
  date_of_birth: '1990-01-01',
  address: '123 Main St',
  city: 'Anytown',
  state: 'CA',
  zip_code: '12345',
};

export const mockCheckInHistory: CheckInHistory[] = [
  { id: 1, date: '2024-01-15', time: '09:30 AM', status: 'checked-in' },
  { id: 2, date: '2024-01-15', time: '11:45 AM', status: 'checked-out' },
  { id: 3, date: '2024-01-14', time: '08:15 AM', status: 'checked-in' },
  { id: 4, date: '2024-01-14', time: '10:30 AM', status: 'checked-out' },
  { id: 5, date: '2024-01-13', time: '07:45 AM', status: 'checked-in' },
];

export const mockClassesTaken: ClassTaken[] = [
  {
    id: 1,
    className: 'Morning Yoga',
    instructor: 'Sarah Johnson',
    date: '2024-01-15',
    time: '10:00 AM',
    status: 'completed',
  },
  {
    id: 2,
    className: 'HIIT Training',
    instructor: 'Mike Wilson',
    date: '2024-01-14',
    time: '09:00 AM',
    status: 'completed',
  },
  { id: 3, className: 'Pilates', instructor: 'Emily Davis', date: '2024-01-16', time: '11:00 AM', status: 'upcoming' },
  {
    id: 4,
    className: 'Spin Class',
    instructor: 'David Brown',
    date: '2024-01-13',
    time: '06:30 PM',
    status: 'completed',
  },
  { id: 5, className: 'Zumba', instructor: 'Lisa Martinez', date: '2024-01-12', time: '07:00 PM', status: 'cancelled' },
];

export const mockPastInvoices: Invoice[] = [
  {
    id: 1,
    invoiceNumber: 'INV-2024-001',
    date: '2024-01-01',
    amount: 49.99,
    description: 'Monthly Membership Fee',
    status: 'paid',
  },
  {
    id: 2,
    invoiceNumber: 'INV-2023-012',
    date: '2023-12-01',
    amount: 49.99,
    description: 'Monthly Membership Fee',
    status: 'paid',
  },
  {
    id: 3,
    invoiceNumber: 'INV-2023-011',
    date: '2023-11-01',
    amount: 49.99,
    description: 'Monthly Membership Fee',
    status: 'paid',
  },
  {
    id: 4,
    invoiceNumber: 'INV-2023-010',
    date: '2023-10-01',
    amount: 49.99,
    description: 'Monthly Membership Fee',
    status: 'paid',
  },
  {
    id: 5,
    invoiceNumber: 'INV-2023-009',
    date: '2023-09-15',
    amount: 25.0,
    description: 'Personal Training Session',
    status: 'paid',
  },
];

export const mockProducts: Product[] = [
  {
    product_id: 'mock-1',
    name: 'Product 1',
    product_description: 'Product 1 Description',
    product_image: '/cafe_stock_assets/ProteinBar.jpg',
    number_sold: 10,
    quantity: 100,
    price: 10.99,
    category: 'protein_bar' as const,
    min_quantity: 5,
    restock: false,
    is_active: true,
    sku: 'SKU-001',
  },
  {
    product_id: 'mock-2',
    name: 'Product 2',
    product_description: 'Product 2 Description',
    product_image: '/cafe_stock_assets/SportsDrink.jpg',
    number_sold: 20,
    quantity: 200,
    price: 20.5,
    category: 'drink' as const,
    min_quantity: 5,
    restock: false,
    is_active: true,
    sku: 'SKU-002',
  },
  {
    product_id: 'mock-3',
    name: 'Product 3',
    product_description: 'Product 3 Description',
    product_image: '/cafe_stock_assets/ProteinBar.jpg',
    number_sold: 30,
    quantity: 300,
    price: 30.75,
    category: 'protein_bar' as const,
    min_quantity: 5,
    restock: false,
    is_active: true,
    sku: 'SKU-003',
  },
  {
    product_id: 'mock-4',
    name: 'Product 4',
    product_description: 'Product 4 Description',
    product_image: '/cafe_stock_assets/SportsDrink.jpg',
    number_sold: 40,
    quantity: 400,
    price: 40.25,
    category: 'drink' as const,
    min_quantity: 5,
    restock: false,
    is_active: true,
    sku: 'SKU-004',
  },
  {
    product_id: 'mock-5',
    name: 'Product 5',
    product_description: 'Product 5 Description',
    product_image: '/cafe_stock_assets/ProteinBar.jpg',
    number_sold: 50,
    quantity: 500,
    price: 50.0,
    category: 'protein_bar' as const,
    min_quantity: 5,
    restock: false,
    is_active: true,
    sku: 'SKU-005',
  },
  {
    product_id: 'mock-6',
    name: 'Product 6',
    product_description: 'Product 6 Description',
    product_image: '/cafe_stock_assets/SportsDrink.jpg',
    number_sold: 60,
    quantity: 600,
    price: 60.95,
    category: 'drink' as const,
    min_quantity: 5,
    restock: false,
    is_active: true,
    sku: 'SKU-006',
  },
];

export const mockProduct = {
  id: 1,
  name: 'Espresso',
  price: 4.5,
  image: 'https://via.placeholder.com/400x300',
  description: 'Strong coffee shot with rich flavor and aromatic notes. Perfect for energy boost.',
  nutritionalInfo: 'Calories: 5 | Caffeine: 63mg | Fat: 0g | Carbs: 1g',
};

export const mockClasses: ClassScheduleItem[] = [
  {
    class_id: '1',
    class_name: 'Morning Yoga',
    time: '09:00:00',
    category: 'yoga',
    scheduled_on: '2025-01-01',
    coach_id: 'coach1',
    day: 1,
    duration: 60,
    capacity: 20,
    created_at: '2025-01-01T09:00:00Z',
    is_active: true,
    coaches: {
      first_name: 'John',
      last_name: 'Doe',
    },
  },
  {
    class_id: '2',
    class_name: 'HIIT Training',
    time: '11:00:00',
    category: 'hiit',
    scheduled_on: '2025-01-01',
    coach_id: 'coach2',
    day: 1,
    duration: 45,
    capacity: 15,
    created_at: '2025-01-01T11:00:00Z',
    is_active: true,
    coaches: {
      first_name: 'Jane',
      last_name: 'Smith',
    },
  },
  {
    class_id: '3',
    class_name: 'Power Cycle',
    time: '12:00:00',
    category: 'cardio',
    scheduled_on: '2025-01-01',
    coach_id: 'coach3',
    day: 1,
    duration: 50,
    capacity: 20,
    created_at: '2025-01-01T12:00:00Z',
    is_active: true,
    coaches: {
      first_name: 'Mike',
      last_name: 'Johnson',
    },
  },
  {
    class_id: '4',
    class_name: 'Aqua Fitness',
    time: '10:00:00',
    category: 'aquatic',
    scheduled_on: '2025-01-01',
    coach_id: 'coach4',
    day: 1,
    duration: 60,
    capacity: 12,
    created_at: '2025-01-01T10:00:00Z',
    is_active: true,
    coaches: {
      first_name: 'Sarah',
      last_name: 'Wilson',
    },
  },
];
export const mockEnrolledClasses: EnrolledBooking[] = [
  {
    class_id: 'mock-1',
    booking_status: 'scheduled',
    waitlisted: false,
    joined_at: new Date().toISOString(),
    class_details: {
      class_name: 'Mock Yoga Class',
      category: 'Yoga',
      scheduled_on: '2025-08-01',
      time: '14:00:00',
    },
  },
  {
    class_id: 'mock-2',
    booking_status: 'scheduled',
    waitlisted: false,
    joined_at: new Date().toISOString(),
    class_details: {
      class_name: 'Mock Spin Class',
      category: 'Cycling',
      scheduled_on: '2025-08-02',
      time: '10:00:00',
    },
  },
];

export const mockStatisticsCards: AnalyticsStatistic[] = [
  {
    stat_id: '1',
    title: 'totalMembers',
    value: 2400,
    percentage_change: 4.5,
    increase: true,
    icon_name: 'totalMembers',
  },
  {
    stat_id: '2',
    title: 'revenue',
    value: 42800,
    percentage_change: 2.1,
    increase: false,
    icon_name: 'revenue',
  },
  {
    stat_id: '3',
    title: 'activeUsers',
    value: 1345,
    percentage_change: -3.2,
    increase: false,
    icon_name: 'activeUsers',
  },
  {
    stat_id: '4',
    title: 'newUsers',
    value: 98,
    percentage_change: 6.8,
    increase: true,
    icon_name: 'newUsers',
  },
];

export const mockMembershipGrowth: MembershipGrowth[] = [
  { month: 'Jan', percentage_growth: 12 },
  { month: 'Feb', percentage_growth: 15 },
  { month: 'Mar', percentage_growth: 18 },
  { month: 'Apr', percentage_growth: 20 },
  { month: 'May', percentage_growth: 14 },
  { month: 'Jun', percentage_growth: 22 },
];

export const mockClassAttendance: ClassAttendance[] = [
  { class_type: 'Yoga', visits: 120 },
  { class_type: 'HIIT', visits: 90 },
  { class_type: 'Cycling', visits: 75 },
  { class_type: 'Boxing', visits: 110 },
];

export const mockTargetRevenue: TargetRevenue = {
  achieved: 28000,
  target: 42000,
};

export const mockActiveHours: ActiveHours[] = [
  { hour: '6 AM', active_users: 45 },
  { hour: '8 AM', active_users: 72 },
  { hour: '10 AM', active_users: 53 },
  { hour: '12 PM', active_users: 95 },
  { hour: '2 PM', active_users: 38 },
  { hour: '4 PM', active_users: 87 },
  { hour: '6 PM', active_users: 102 },
  { hour: '8 PM', active_users: 76 },
];

export const mockDashClasses = [
  {
    class_id: 'dummy-1',
    category: 'yoga',
    coach: [{ first_name: 'Mock' }],
    time: '07:00:00',
    capacity: 10,
  },
  {
    class_id: 'dummy-12',
    category: 'Cycling',
    coach: [{ first_name: 'Mock' }],
    time: '08:30:00',
    capacity: 15,
  },
  {
    class_id: 'dummy-2',
    category: 'Hiit',
    coach: [{ first_name: 'Mock' }],
    time: '09:00:00',
    capacity: 15,
  },
  {
    class_id: 'dummy-3',
    category: 'aquatic',
    coach: [{ first_name: 'Mock' }],
    time: '10:30:00',
    capacity: 15,
  },
  {
    class_id: 'dummy-4',
    category: 'boxing',
    coach: [{ first_name: 'Mock' }],
    time: '14:30:00',
    capacity: 15,
  },
];