import {
  CheckInHistory,
  ClassScheduleItem,
  ClassTaken,
  EnrolledBooking,
  Invoice,
  Member,
  Product,
} from '@/types/shared';

// Mock data for Member Detail Page - In a real app, this would come from an API
export const mockMember: Member = {
  user_id: '1',
  first_name: 'John',
  last_name: 'Doe',
  email: 'john.doe@example.com',
  phone: '1234567890',
  membership_plan: 'Basic',
  created_at: '2021-01-01',
  user_image: '',
  role_name: 'member',
  date_of_birth: '1990-01-01',
  address: '123 Main St',
  city: 'Anytown',
  state: 'CA',
  zip_code: '12345',
};

export const mockMembersData: Member[] = [
  {
    user_id: '1',
    first_name: 'John',
    last_name: 'Smith',
    email: 'john.smith@email.com',
    phone: '(555) 123-4567',
    user_image: 'https://ui-avatars.com/api/?name=John+Smith',
    role_name: 'member',
    date_of_birth: '1990-01-01',
    address: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zip_code: '12345',
    membership_plan: 'Basic',
    created_at: '2021-01-01',
  },
  {
    user_id: '2',
    first_name: 'Sarah',
    last_name: 'Johnson',
    email: 'sarah.johnson@email.com',
    phone: '(555) 234-5678',
    user_image: 'https://ui-avatars.com/api/?name=Sarah+Johnson',
    role_name: 'member',
    date_of_birth: '1990-01-01',
    address: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zip_code: '12345',
    membership_plan: 'Basic',
    created_at: '2021-01-01',
  },
  {
    user_id: '3',
    first_name: 'Mike',
    last_name: 'Wilson',
    email: 'mike.wilson@email.com',
    phone: '(555) 345-6789',
    user_image: 'https://ui-avatars.com/api/?name=Mike+Wilson',
    role_name: 'member',
    date_of_birth: '1990-01-01',
    address: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zip_code: '12345',
    membership_plan: 'Basic',
    created_at: '2021-01-01',
  },
];

export const mockCheckInHistory: CheckInHistory[] = [
  { id: 1, date: '2024-01-15', time: '09:30 AM', status: 'checked-in' },
  { id: 2, date: '2024-01-15', time: '11:45 AM', status: 'checked-out' },
  { id: 3, date: '2024-01-14', time: '08:15 AM', status: 'checked-in' },
  { id: 4, date: '2024-01-14', time: '10:30 AM', status: 'checked-out' },
  { id: 5, date: '2024-01-13', time: '07:45 AM', status: 'checked-in' },
];

export const mockClassesTaken: ClassTaken[] = [
  {
    id: 1,
    className: 'Morning Yoga',
    instructor: 'Sarah Johnson',
    date: '2024-01-15',
    time: '10:00 AM',
    status: 'completed',
  },
  {
    id: 2,
    className: 'HIIT Training',
    instructor: 'Mike Wilson',
    date: '2024-01-14',
    time: '09:00 AM',
    status: 'completed',
  },
  { id: 3, className: 'Pilates', instructor: 'Emily Davis', date: '2024-01-16', time: '11:00 AM', status: 'upcoming' },
  {
    id: 4,
    className: 'Spin Class',
    instructor: 'David Brown',
    date: '2024-01-13',
    time: '06:30 PM',
    status: 'completed',
  },
  { id: 5, className: 'Zumba', instructor: 'Lisa Martinez', date: '2024-01-12', time: '07:00 PM', status: 'cancelled' },
];

export const mockPastInvoices: Invoice[] = [
  {
    id: 1,
    invoiceNumber: 'INV-2024-001',
    date: '2024-01-01',
    amount: 49.99,
    description: 'Monthly Membership Fee',
    status: 'paid',
  },
  {
    id: 2,
    invoiceNumber: 'INV-2023-012',
    date: '2023-12-01',
    amount: 49.99,
    description: 'Monthly Membership Fee',
    status: 'paid',
  },
  {
    id: 3,
    invoiceNumber: 'INV-2023-011',
    date: '2023-11-01',
    amount: 49.99,
    description: 'Monthly Membership Fee',
    status: 'paid',
  },
  {
    id: 4,
    invoiceNumber: 'INV-2023-010',
    date: '2023-10-01',
    amount: 49.99,
    description: 'Monthly Membership Fee',
    status: 'paid',
  },
  {
    id: 5,
    invoiceNumber: 'INV-2023-009',
    date: '2023-09-15',
    amount: 25.0,
    description: 'Personal Training Session',
    status: 'paid',
  },
];

export const mockProducts: Product[] = [
  {
    product_id: 'mock-1',
    name: 'Product 1',
    product_description: 'Product 1 Description',
    product_image: '/cafe_stock_assets/ProteinBar.jpg',
    number_sold: 10,
    quantity: 100,
    price: 10.99,
    category: 'protein_bar' as const,
    min_quantity: 5,
    restock: false,
    is_active: true,
    sku: 'SKU-001',
  },
  {
    product_id: 'mock-2',
    name: 'Product 2',
    product_description: 'Product 2 Description',
    product_image: '/cafe_stock_assets/SportsDrink.jpg',
    number_sold: 20,
    quantity: 200,
    price: 20.5,
    category: 'drink' as const,
    min_quantity: 5,
    restock: false,
    is_active: true,
    sku: 'SKU-002',
  },
  {
    product_id: 'mock-3',
    name: 'Product 3',
    product_description: 'Product 3 Description',
    product_image: '/cafe_stock_assets/ProteinBar.jpg',
    number_sold: 30,
    quantity: 300,
    price: 30.75,
    category: 'protein_bar' as const,
    min_quantity: 5,
    restock: false,
    is_active: true,
    sku: 'SKU-003',
  },
  {
    product_id: 'mock-4',
    name: 'Product 4',
    product_description: 'Product 4 Description',
    product_image: '/cafe_stock_assets/SportsDrink.jpg',
    number_sold: 40,
    quantity: 400,
    price: 40.25,
    category: 'drink' as const,
    min_quantity: 5,
    restock: false,
    is_active: true,
    sku: 'SKU-004',
  },
  {
    product_id: 'mock-5',
    name: 'Product 5',
    product_description: 'Product 5 Description',
    product_image: '/cafe_stock_assets/ProteinBar.jpg',
    number_sold: 50,
    quantity: 500,
    price: 50.0,
    category: 'protein_bar' as const,
    min_quantity: 5,
    restock: false,
    is_active: true,
    sku: 'SKU-005',
  },
  {
    product_id: 'mock-6',
    name: 'Product 6',
    product_description: 'Product 6 Description',
    product_image: '/cafe_stock_assets/SportsDrink.jpg',
    number_sold: 60,
    quantity: 600,
    price: 60.95,
    category: 'drink' as const,
    min_quantity: 5,
    restock: false,
    is_active: true,
    sku: 'SKU-006',
  },
];

export const mockClasses: ClassScheduleItem[] = [
  {
    class_id: '1',
    class_name: 'Morning Yoga',
    time: '09:00:00',
    category: 'yoga',
    scheduled_on: '2025-01-01',
    coach_id: 'coach1',
    day: 1,
    duration: 60,
    capacity: 20,
    created_at: '2025-01-01T09:00:00Z',
    is_active: true,
    coaches: {
      first_name: 'John',
      last_name: 'Doe',
    },
  },
  {
    class_id: '2',
    class_name: 'HIIT Training',
    time: '11:00:00',
    category: 'hiit',
    scheduled_on: '2025-01-01',
    coach_id: 'coach2',
    day: 1,
    duration: 45,
    capacity: 15,
    created_at: '2025-01-01T11:00:00Z',
    is_active: true,
    coaches: {
      first_name: 'Jane',
      last_name: 'Smith',
    },
  },
  {
    class_id: '3',
    class_name: 'Power Cycle',
    time: '12:00:00',
    category: 'cardio',
    scheduled_on: '2025-01-01',
    coach_id: 'coach3',
    day: 1,
    duration: 50,
    capacity: 20,
    created_at: '2025-01-01T12:00:00Z',
    is_active: true,
    coaches: {
      first_name: 'Mike',
      last_name: 'Johnson',
    },
  },
  {
    class_id: '4',
    class_name: 'Aqua Fitness',
    time: '10:00:00',
    category: 'aquatic',
    scheduled_on: '2025-01-01',
    coach_id: 'coach4',
    day: 1,
    duration: 60,
    capacity: 12,
    created_at: '2025-01-01T10:00:00Z',
    is_active: true,
    coaches: {
      first_name: 'Sarah',
      last_name: 'Wilson',
    },
  },
];
export const mockEnrolledClasses: EnrolledBooking[] = [
  {
    class_id: 'mock-1',
    booking_status: 'scheduled',
    waitlisted: false,
    joined_at: new Date().toISOString(),
    class_details: {
      class_name: 'Mock Yoga Class',
      category: 'Yoga',
      scheduled_on: '2025-08-01',
      time: '14:00:00',
    },
  },
  {
    class_id: 'mock-2',
    booking_status: 'scheduled',
    waitlisted: false,
    joined_at: new Date().toISOString(),
    class_details: {
      class_name: 'Mock Spin Class',
      category: 'Cycling',
      scheduled_on: '2025-08-02',
      time: '10:00:00',
    },
  },
];
